export const UtilTypes = {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_THEME: 'CHANGE_THEME',
    IS_CHANGE_THEME: 'IS_CHANGE_THEME',

    ///ACTION DEMO
    DEMO_ACTION: 'DEMO_ACTION',
    DEMO_ACTION_SUCCESS: 'DEMO_ACTION_SUCCESS',

    ///ACTION CALL API
    DEMO_CALL_API: 'DEMO_CALL_API',
    DEMO_CALL_API_SUCCESS: 'DEMO_CALL_API_SUCCESS',
}